version: "3.9"

services:
  database:
    container_name: mail-sender-database
    image: mariadb
    volumes:
      - ./docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ./docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3307:3306"

  application:
    container_name: mail-sender-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
