jwt:
  secret: "12345678901234567890123456789012"

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:~/data/local/mail-sender
  jpa:
    hibernate:
      ddl-auto: create
